// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.arkadias.html5.domain;

import com.arkadias.html5.domain.MessageFormIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MessageFormIntegrationTest_Roo_Configurable {
    
    declare @type: MessageFormIntegrationTest: @Configurable;
    
}
